### ISSUE TITLE
Can't load 'std.cfg' because 'FILESDIR' is hard coded

### ISSUE THREAD

**Issue by lcarcaramo** [ZOSOpenTools/cppcheckport#2]
I installed the z/OS Open Tools port of `cppcheck` from the provided fax file. It appears that `cppcheck` is unable to load `std.cfg` becasue `FILESDIR` is hard coded.

```console
$ cppcheck hello.cc
cppcheck: Failed to load library configuration file 'std.cfg'. File not found
Failed to load std.cfg. Your Cppcheck installation is broken, please re-install. The Cppcheck binary was compiled with FILESDIR set to "/jenkins/zopen/usr/local/zopen/cppcheck/cppcheck-main/share/Cppcheck" and will therefore search for std.cfg in /jenkins/zopen/usr/local/zopen/cppcheck/cppcheck-main/share/Cppcheck/cfg.
```

The following workaround also does not work:
```console
$ cppcheck --library=/path/to/install-dir/cppcheck-main/share/Cppcheck/cfg/cppcheck-lib.cfg hello.cc
cppcheck: Failed to load library configuration file 'std.cfg'. File not found
Failed to load std.cfg. Your Cppcheck installation is broken, please re-install. The Cppcheck binary was compiled with FILESDIR set to "/jenkins/zopen/usr/local/zopen/cppcheck/cppcheck-main/share/Cppcheck" and will therefore search for std.cfg in /jenkins/zopen/usr/local/zopen/cppcheck/cppcheck-main/share/Cppcheck/cfg.
```

**Comment by AnthonyGiorgio** [comment]
I'm looking forward to trying this out on z/OS.  It might make for a useful addition to the ZOAU CICD pipeline.

**Comment by IgorTodorovskiIBM** [comment]
Can you check the latest build? It appears to be working for me

**Comment by AnthonyGiorgio** [comment]
I gave the latest build a try, and it worked with the ZOAU source code.  It didn't like the JSON web toolkit header file that was stored in a dataset, but that was probably due to an encoding issue.  When I switched to the one in the filesystem, it worked fine.

**Comment by lcarcaramo** [comment]
I also tried the latest build, and everything seems to be working with no issues now.
